// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqqmkiocynvlaianwisd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxcW1raW9jeW52bGFpYW53aXNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3MTE1OTgsImV4cCI6MjA4NjI4NzU5OH0.OLlbMOhB43uhP5UFwagGQmaygM8SB8IC5edo4FRicDo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});